#version: "3"
version: "3.9"

services:
  mongodb:
    image: mongo:6.0.6
    restart: always
    volumes:
      - mongodb-data:/data/db
  nginx-proxy:
    # comando para configurar Nginx
    command: "sh -c 'echo \"server_tokens off; proxy_connect_timeout 300; proxy_send_timeout 300; proxy_read_timeout 90m; send_timeout 300;client_max_body_size 1024M;\" > /etc/nginx/conf.d/my_proxy.conf; forego start -r'"
    restart: always               # reiniciar siempre
    image: jwilder/nginx-proxy    # imagen desde docker HUB
    container_name: nginx-proxy   # nombre del contenedor
    ports:                        # Asignacion del puerto 80 al proxy
     - "80:80"
     - "443:443"
    volumes:                      # Entrega información de de Docker 
     - /var/run/docker.sock:/tmp/docker.sock:ro
  backend:  
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - "0.0.0.0:4001:4001/tcp"  # Mapeo para IPv4
    depends_on:
      - mongodb
    networks:
      - red_proxy
      - red_privada
      

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - "0.0.0.0:5173:5173"  # Mapeo para IPv4
 
    networks:
      - red_proxy
      - red_privada

networks:   
  default:
    external:
      name: nginx-proxy    # Definir redes
  red_proxy:               # Nombre de una red
    external:              # Indica que es una red externa al docker-compose
      name: nginx-proxy    # Nombre de la Red de uso publico entre Docker
  red_privada:
    driver_opts:
      com.docker.network.enable_ipv6: "true"

volumes:
  mongodb-data: